<?php

namespace AppBundle\Repository;

/**
 * SchoolclassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolclassRepository extends \Doctrine\ORM\EntityRepository
{
}
