<?php

namespace AppBundle\Repository;

/**
 * UserSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
