<?php

namespace AppBundle\Repository;

/**
 * UserClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserClassRepository extends \Doctrine\ORM\EntityRepository
{
}
